# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatchInserted_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatchInsertedWindow(object):
    def setupUi(self, BatchInsertedWindow):
        BatchInsertedWindow.setObjectName("BatchInsertedWindow")
        BatchInsertedWindow.resize(636, 338)
        self.centralwidget = QtWidgets.QWidget(BatchInsertedWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.batch_insert_button = QtWidgets.QPushButton(self.centralwidget)
        self.batch_insert_button.setGeometry(QtCore.QRect(160, 260, 321, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.batch_insert_button.setFont(font)
        self.batch_insert_button.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #cdced1, stop:1 #f6f7fa);\n"
"    border:1px solid gray;\n"
"border-radius:8px\n"
"}\n"
"QPushButton:hover{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #f6f7fa, stop:1 #cdced1);\n"
"}\n"
"QPushButton:pressed{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #b6b6b6, stop:1 rgb(227, 227, 227));\n"
"}\n"
"")
        self.batch_insert_button.setObjectName("batch_insert_button")
        self.insert_path = QtWidgets.QLineEdit(self.centralwidget)
        self.insert_path.setGeometry(QtCore.QRect(110, 90, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.insert_path.setFont(font)
        self.insert_path.setStyleSheet("QLineEdit{border:0.5px solid gray; }\n"
"")
        self.insert_path.setObjectName("insert_path")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 40, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, -20, 651, 361))
        self.bg.setStyleSheet("Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(51, 156, 235), stop:1 rgb(245, 245, 245))")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 152, 81, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(410, 152, 81, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 160, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 160, 161, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 160, 21, 16))
        self.label_4.setObjectName("label_4")
        self.pbar = QtWidgets.QProgressBar(self.centralwidget)
        self.pbar.setGeometry(QtCore.QRect(109, 210, 451, 23))
        self.pbar.setProperty("value", 0)
        self.pbar.setObjectName("pbar")
        self.bg.raise_()
        self.batch_insert_button.raise_()
        self.insert_path.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pbar.raise_()
        BatchInsertedWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(BatchInsertedWindow)
        QtCore.QMetaObject.connectSlotsByName(BatchInsertedWindow)

    def retranslateUi(self, BatchInsertedWindow):
        _translate = QtCore.QCoreApplication.translate
        BatchInsertedWindow.setWindowTitle(_translate("BatchInsertedWindow", "MainWindow"))
        self.batch_insert_button.setText(_translate("BatchInsertedWindow", "批量插入"))
        self.insert_path.setPlaceholderText(_translate("BatchInsertedWindow", "支持xls、xlsx格式的文件"))
        self.label.setText(_translate("BatchInsertedWindow", "请输入文件路径："))
        self.label_2.setText(_translate("BatchInsertedWindow", "第"))
        self.label_3.setText(_translate("BatchInsertedWindow", "行      --      第"))
        self.label_4.setText(_translate("BatchInsertedWindow", "行"))
