# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Insert_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InsertWindow(object):
    def setupUi(self, InsertWindow):
        InsertWindow.setObjectName("InsertWindow")
        InsertWindow.resize(418, 405)
        self.centralwidget = QtWidgets.QWidget(InsertWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_insert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_insert.setGeometry(QtCore.QRect(50, 320, 321, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_insert.setFont(font)
        self.pushButton_insert.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #cdced1, stop:1 #f6f7fa);\n"
"    border:1px solid gray;\n"
"border-radius:8px\n"
"}\n"
"QPushButton:hover{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #f6f7fa, stop:1 #cdced1);\n"
"}\n"
"QPushButton:pressed{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #b6b6b6, stop:1 rgb(227, 227, 227));\n"
"}\n"
"")
        self.pushButton_insert.setObjectName("pushButton_insert")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 50, 321, 245))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_id.setStyleSheet("QLineEdit{border:0.5px solid gray;}\n"
"")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_id)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_name.setStyleSheet("QLineEdit{border:0.5px solid gray;}\n"
"")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_sex = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_sex.setStyleSheet("QComboBox{border:0.5px solid gray;}\n"
"")
        self.comboBox_sex.setObjectName("comboBox_sex")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_sex)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_college = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_college.setStyleSheet("QComboBox{border:0.5px solid gray;}\n"
"")
        self.comboBox_college.setObjectName("comboBox_college")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_college)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_major = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_major.setStyleSheet("QComboBox{border:0.5px solid gray;}\n"
"")
        self.comboBox_major.setObjectName("comboBox_major")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_major)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_phonenumber = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_phonenumber.setStyleSheet("QLineEdit{border:0.5px solid gray;}\n"
"")
        self.lineEdit_phonenumber.setObjectName("lineEdit_phonenumber")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_phonenumber)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setEnabled(False)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 421, 411))
        self.label_12.setMinimumSize(QtCore.QSize(421, 411))
        self.label_12.setMaximumSize(QtCore.QSize(421, 411))
        self.label_12.setStyleSheet("Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(51, 156, 235), stop:1 rgb(245, 245, 245))")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_12.raise_()
        self.pushButton_insert.raise_()
        self.layoutWidget.raise_()
        InsertWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InsertWindow)
        QtCore.QMetaObject.connectSlotsByName(InsertWindow)

    def retranslateUi(self, InsertWindow):
        _translate = QtCore.QCoreApplication.translate
        InsertWindow.setWindowTitle(_translate("InsertWindow", "MainWindow"))
        self.pushButton_insert.setText(_translate("InsertWindow", "插入记录"))
        self.label.setText(_translate("InsertWindow", "学号："))
        self.label_2.setText(_translate("InsertWindow", "姓名："))
        self.label_3.setText(_translate("InsertWindow", "性别："))
        self.label_4.setText(_translate("InsertWindow", "学院："))
        self.label_5.setText(_translate("InsertWindow", "专业："))
        self.label_6.setText(_translate("InsertWindow", "手机号："))
