# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1120, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1201, 811))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tab_1.setFont(font)
        self.tab_1.setObjectName("tab_1")
        self.pushButton_insert = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_insert.setGeometry(QtCore.QRect(50, 690, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_insert.setFont(font)
        self.pushButton_insert.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #cdced1, stop:1 #f6f7fa);\n"
"    border:1px solid gray;\n"
"border-radius:8px\n"
"}\n"
"QPushButton:hover{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #f6f7fa, stop:1 #cdced1);\n"
"}\n"
"QPushButton:pressed{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #b6b6b6, stop:1 rgb(227, 227, 227));\n"
"}\n"
"")
        self.pushButton_insert.setObjectName("pushButton_insert")
        self.pushButton_delete = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_delete.setGeometry(QtCore.QRect(990, 690, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #cdced1, stop:1 #f6f7fa);\n"
"    border:1px solid gray;\n"
"border-radius:8px\n"
"}\n"
"QPushButton:hover{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #f6f7fa, stop:1 #cdced1);\n"
"}\n"
"QPushButton:pressed{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #b6b6b6, stop:1 rgb(227, 227, 227));\n"
"}\n"
"")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_query = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_query.setGeometry(QtCore.QRect(50, 110, 1091, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_query.setFont(font)
        self.pushButton_query.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #cdced1, stop:1 #f6f7fa);\n"
"    border:1px solid gray;\n"
"border-radius:8px\n"
"}\n"
"QPushButton:hover{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #f6f7fa, stop:1 #cdced1);\n"
"}\n"
"QPushButton:pressed{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #b6b6b6, stop:1 rgb(227, 227, 227));\n"
"}\n"
"")
        self.pushButton_query.setObjectName("pushButton_query")
        self.pushButton_batch = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_batch.setGeometry(QtCore.QRect(530, 690, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_batch.setFont(font)
        self.pushButton_batch.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #cdced1, stop:1 #f6f7fa);\n"
"    border:1px solid gray;\n"
"border-radius:8px\n"
"}\n"
"QPushButton:hover{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #f6f7fa, stop:1 #cdced1);\n"
"}\n"
"QPushButton:pressed{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #b6b6b6, stop:1 rgb(227, 227, 227));\n"
"}\n"
"")
        self.pushButton_batch.setObjectName("pushButton_batch")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget.setGeometry(QtCore.QRect(50, 180, 1091, 481))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_12 = QtWidgets.QLabel(self.tab_1)
        self.label_12.setEnabled(False)
        self.label_12.setGeometry(QtCore.QRect(-19, -60, 1251, 861))
        self.label_12.setStyleSheet("Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(51, 156, 235), stop:1 rgb(245, 245, 245))")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(390, 45, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_id = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_id.setGeometry(QtCore.QRect(90, 45, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setStyleSheet("QLineEdit{border:0.5px solid gray;}\n"
"")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setGeometry(QtCore.QRect(500, 45, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox_sex = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_sex.setGeometry(QtCore.QRect(440, 45, 51, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        self.comboBox_sex.setFont(font)
        self.comboBox_sex.setStyleSheet("QComboBox{border:0.5px solid gray; }\n"
"")
        self.comboBox_sex.setObjectName("comboBox_sex")
        self.comboBox_major = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_major.setGeometry(QtCore.QRect(750, 45, 171, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        self.comboBox_major.setFont(font)
        self.comboBox_major.setStyleSheet("QComboBox{border:0.5px solid gray; }\n"
"")
        self.comboBox_major.setObjectName("comboBox_major")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(40, 45, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setGeometry(QtCore.QRect(920, 45, 90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.comboBox_college = QtWidgets.QComboBox(self.tab_1)
        self.comboBox_college.setGeometry(QtCore.QRect(550, 45, 141, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        self.comboBox_college.setFont(font)
        self.comboBox_college.setStyleSheet("QComboBox{border:0.5px solid gray;}\n"
"")
        self.comboBox_college.setObjectName("comboBox_college")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(240, 45, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_phonenumber = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_phonenumber.setGeometry(QtCore.QRect(1000, 45, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_phonenumber.setFont(font)
        self.lineEdit_phonenumber.setStyleSheet("QLineEdit{border:0.5px solid gray; }\n"
"")
        self.lineEdit_phonenumber.setObjectName("lineEdit_phonenumber")
        self.lineEdit_name = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_name.setGeometry(QtCore.QRect(290, 45, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setStyleSheet("QLineEdit{border:0.5px solid gray;}\n"
"")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setGeometry(QtCore.QRect(700, 44, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_12.raise_()
        self.label_3.raise_()
        self.lineEdit_id.raise_()
        self.label_4.raise_()
        self.comboBox_sex.raise_()
        self.comboBox_major.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.comboBox_college.raise_()
        self.label_2.raise_()
        self.lineEdit_phonenumber.raise_()
        self.lineEdit_name.raise_()
        self.label_5.raise_()
        self.pushButton_insert.raise_()
        self.pushButton_delete.raise_()
        self.pushButton_query.raise_()
        self.pushButton_batch.raise_()
        self.tableWidget.raise_()
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tab_2.setFont(font)
        self.tab_2.setAccessibleName("")
        self.tab_2.setObjectName("tab_2")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(0, -10, 1211, 801))
        self.label_9.setStyleSheet("Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(51, 156, 235), stop:1 rgb(245, 245, 245))")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.pushButton_query_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_query_2.setGeometry(QtCore.QRect(50, 110, 1091, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButton_query_2.setFont(font)
        self.pushButton_query_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #cdced1, stop:1 #f6f7fa);\n"
"    border:1px solid gray;\n"
"border-radius:8px\n"
"}\n"
"QPushButton:hover{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #f6f7fa, stop:1 #cdced1);\n"
"}\n"
"QPushButton:pressed{\n"
"    Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #b6b6b6, stop:1 rgb(227, 227, 227));\n"
"}\n"
"")
        self.pushButton_query_2.setObjectName("pushButton_query_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(50, 180, 1091, 531))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.comboBox_sex_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_sex_2.setGeometry(QtCore.QRect(1000, 45, 141, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        self.comboBox_sex_2.setFont(font)
        self.comboBox_sex_2.setStyleSheet("QComboBox{border:0.5px solid gray; }\n"
"")
        self.comboBox_sex_2.setObjectName("comboBox_sex_2")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(520, 45, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(900, 45, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QComboBox{border:0.5px solid gray; border-radius:8px}\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_id_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_id_2.setGeometry(QtCore.QRect(90, 45, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_id_2.setFont(font)
        self.lineEdit_id_2.setStyleSheet("QLineEdit{border:0.5px solid gray;}\n"
"")
        self.lineEdit_id_2.setObjectName("lineEdit_id_2")
        self.lineEdit_name_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_name_2.setGeometry(QtCore.QRect(580, 45, 91, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        self.lineEdit_name_2.setFont(font)
        self.lineEdit_name_2.setStyleSheet("QLineEdit{border:0.5px solid gray; }\n"
"")
        self.lineEdit_name_2.setObjectName("lineEdit_name_2")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(40, 45, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tab_3.setFont(font)
        self.tab_3.setObjectName("tab_3")
        self.bg = QtWidgets.QLabel(self.tab_3)
        self.bg.setGeometry(QtCore.QRect(0, -70, 1241, 861))
        self.bg.setStyleSheet("Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(51, 156, 235), stop:1 rgb(245, 245, 245))")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(370, 230, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.top_up_id = QtWidgets.QLineEdit(self.tab_3)
        self.top_up_id.setGeometry(QtCore.QRect(510, 230, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.top_up_id.setFont(font)
        self.top_up_id.setStyleSheet("QLineEdit{border:0.5px solid gray; border-radius:8px}\n"
"")
        self.top_up_id.setObjectName("top_up_id")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(370, 340, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_11.setObjectName("label_11")
        self.top_up_money = QtWidgets.QLineEdit(self.tab_3)
        self.top_up_money.setGeometry(QtCore.QRect(510, 340, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.top_up_money.setFont(font)
        self.top_up_money.setStyleSheet("QLineEdit{border:0.5px solid gray; border-radius:8px}\n"
"")
        self.top_up_money.setText("")
        self.top_up_money.setPlaceholderText("")
        self.top_up_money.setObjectName("top_up_money")
        self.top_up_button = QtWidgets.QPushButton(self.tab_3)
        self.top_up_button.setGeometry(QtCore.QRect(400, 470, 411, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.top_up_button.setFont(font)
        self.top_up_button.setStyleSheet("QPushButton{color: rgb(255, 255, 255); background-color: #1dc5fc; border-radius:8px}\n"
"\n"
"QPushButton:hover{Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #23cdfc, stop:1 #1cd7fc);}\n"
"\n"
"QPushButton:pressed{Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #1cd7fc, stop:1 #23cdfc);}\n"
"")
        self.top_up_button.setObjectName("top_up_button")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tab_4.setFont(font)
        self.tab_4.setObjectName("tab_4")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(-30, 0, 1261, 765))
        self.label_13.setStyleSheet("image: url(:/background/JUST.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(150, 230, 891, 321))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 60%);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(480, 100, 241, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(30)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_insert.setText(_translate("MainWindow", "插入记录"))
        self.pushButton_delete.setText(_translate("MainWindow", "删除记录"))
        self.pushButton_query.setText(_translate("MainWindow", "查询记录"))
        self.pushButton_batch.setText(_translate("MainWindow", "批量插入"))
        self.label_3.setText(_translate("MainWindow", "性别："))
        self.label_4.setText(_translate("MainWindow", "学院："))
        self.label.setText(_translate("MainWindow", "学号："))
        self.label_6.setText(_translate("MainWindow", "手机号："))
        self.label_2.setText(_translate("MainWindow", "姓名："))
        self.label_5.setText(_translate("MainWindow", "专业："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "学生基本信息"))
        self.pushButton_query_2.setText(_translate("MainWindow", "查询记录"))
        self.label_17.setText(_translate("MainWindow", "姓名："))
        self.label_7.setText(_translate("MainWindow", "消费类型："))
        self.label_14.setText(_translate("MainWindow", "学号："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "交易记录"))
        self.label_10.setText(_translate("MainWindow", "学      号："))
        self.label_11.setText(_translate("MainWindow", "充值金额："))
        self.top_up_button.setText(_translate("MainWindow", "确认充值"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "账户充值"))
        self.label_8.setText(_translate("MainWindow", "One Card Management System v1.1 2020.12.24\n"
"\n"
"本软件为校园卡管理部门提供了一个操作便捷的数据管理平台\n"
"\n"
"Copyright© LuoHan_YinYue_LiuShuai_LiLinQing. All Rights Reserved."))
        self.label_15.setText(_translate("MainWindow", "About"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "关于"))
import background_rc
