# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Reset_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResetWindow(object):
    def setupUi(self, ResetWindow):
        ResetWindow.setObjectName("ResetWindow")
        ResetWindow.resize(669, 505)
        ResetWindow.setMinimumSize(QtCore.QSize(669, 505))
        ResetWindow.setMaximumSize(QtCore.QSize(669, 505))
        self.centralwidget = QtWidgets.QWidget(ResetWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(610, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("QPushButton{color: rgb(255, 255, 255); border-radius:10px}\n"
"\n"
"QPushButton:hover{Background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));}\n"
"\n"
"QPushButton:pressed{Background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:0.1 rgba(255, 255, 255, 255), stop:0.2 rgba(255, 176, 176, 167), stop:0.3 rgba(255, 151, 151, 92), stop:0.4 rgba(255, 125, 125, 51), stop:0.5 rgba(255, 76, 76, 205), stop:0.52 rgba(255, 76, 76, 205), stop:0.6 rgba(255, 180, 180, 84), stop:1 rgba(255, 255, 255, 0));}")
        self.close_button.setObjectName("close_button")
        self.new_password = QtWidgets.QLabel(self.centralwidget)
        self.new_password.setGeometry(QtCore.QRect(110, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.new_password.setFont(font)
        self.new_password.setAlignment(QtCore.Qt.AlignCenter)
        self.new_password.setObjectName("new_password")
        self.input_pass1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_pass1.setGeometry(QtCore.QRect(220, 210, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_pass1.setFont(font)
        self.input_pass1.setStyleSheet("QLineEdit{border:0.5px solid gray; border-radius:8px}\n"
"")
        self.input_pass1.setText("")
        self.input_pass1.setObjectName("input_pass1")
        self.input_pass2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_pass2.setGeometry(QtCore.QRect(220, 290, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_pass2.setFont(font)
        self.input_pass2.setStyleSheet("QLineEdit{border:0.5px solid gray; border-radius:8px}")
        self.input_pass2.setText("")
        self.input_pass2.setObjectName("input_pass2")
        self.confirm_password = QtWidgets.QLabel(self.centralwidget)
        self.confirm_password.setGeometry(QtCore.QRect(90, 290, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.confirm_password.setFont(font)
        self.confirm_password.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_password.setObjectName("confirm_password")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setEnabled(False)
        self.bg.setGeometry(QtCore.QRect(0, 0, 681, 511))
        self.bg.setStyleSheet("Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(51, 156, 235), stop:1 rgb(245, 245, 245))")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(170, 370, 381, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.submit_button.setFont(font)
        self.submit_button.setStyleSheet("QPushButton{color: rgb(255, 255, 255); background-color: #1dc5fc; border-radius:8px}\n"
"\n"
"QPushButton:hover{Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #23cdfc, stop:1 #1cd7fc);}\n"
"\n"
"QPushButton:pressed{Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #1cd7fc, stop:1 #23cdfc);}\n"
"")
        self.submit_button.setObjectName("submit_button")
        self.text_label = QtWidgets.QLabel(self.centralwidget)
        self.text_label.setGeometry(QtCore.QRect(270, 90, 171, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(21)
        self.text_label.setFont(font)
        self.text_label.setObjectName("text_label")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(30, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet("QPushButton{color: rgb(255, 255, 255); border-radius:10px}\n"
"\n"
"QPushButton:hover{Background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));}\n"
"\n"
"QPushButton:pressed{Background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:0.1 rgba(255, 255, 255, 255), stop:0.2 rgba(255, 176, 176, 167), stop:0.3 rgba(255, 151, 151, 92), stop:0.4 rgba(255, 125, 125, 51), stop:0.5 rgba(255, 76, 76, 205), stop:0.52 rgba(255, 76, 76, 205), stop:0.6 rgba(255, 180, 180, 84), stop:1 rgba(255, 255, 255, 0));}")
        self.back_button.setFlat(True)
        self.back_button.setObjectName("back_button")
        self.bg.raise_()
        self.close_button.raise_()
        self.new_password.raise_()
        self.input_pass1.raise_()
        self.input_pass2.raise_()
        self.confirm_password.raise_()
        self.submit_button.raise_()
        self.text_label.raise_()
        self.back_button.raise_()
        ResetWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ResetWindow)
        QtCore.QMetaObject.connectSlotsByName(ResetWindow)

    def retranslateUi(self, ResetWindow):
        _translate = QtCore.QCoreApplication.translate
        ResetWindow.setWindowTitle(_translate("ResetWindow", "MainWindow"))
        self.close_button.setText(_translate("ResetWindow", "×"))
        self.new_password.setText(_translate("ResetWindow", "新密码："))
        self.input_pass1.setPlaceholderText(_translate("ResetWindow", "请输入新密码"))
        self.input_pass2.setPlaceholderText(_translate("ResetWindow", "请再次输入新密码"))
        self.confirm_password.setText(_translate("ResetWindow", "确认密码："))
        self.submit_button.setText(_translate("ResetWindow", "提交"))
        self.text_label.setText(_translate("ResetWindow", "重置密码"))
        self.back_button.setText(_translate("ResetWindow", "←"))
