# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecurityQuestion_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecurityQuestionWindow(object):
    def setupUi(self, SecurityQuestionWindow):
        SecurityQuestionWindow.setObjectName("SecurityQuestionWindow")
        SecurityQuestionWindow.resize(669, 505)
        SecurityQuestionWindow.setMinimumSize(QtCore.QSize(669, 505))
        SecurityQuestionWindow.setMaximumSize(QtCore.QSize(669, 16777215))
        self.centralwidget = QtWidgets.QWidget(SecurityQuestionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(620, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("QPushButton{color: rgb(255, 255, 255); border-radius:10px}\n"
"\n"
"QPushButton:hover{Background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));}\n"
"\n"
"QPushButton:pressed{Background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:0.1 rgba(255, 255, 255, 255), stop:0.2 rgba(255, 176, 176, 167), stop:0.3 rgba(255, 151, 151, 92), stop:0.4 rgba(255, 125, 125, 51), stop:0.5 rgba(255, 76, 76, 205), stop:0.52 rgba(255, 76, 76, 205), stop:0.6 rgba(255, 180, 180, 84), stop:1 rgba(255, 255, 255, 0));}")
        self.close_button.setObjectName("close_button")
        self.username = QtWidgets.QLabel(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(130, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.username.setFont(font)
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.input_username = QtWidgets.QLineEdit(self.centralwidget)
        self.input_username.setGeometry(QtCore.QRect(210, 210, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_username.setFont(font)
        self.input_username.setStyleSheet("QLineEdit{border:0.5px solid gray; border-radius:8px}\n"
"")
        self.input_username.setText("")
        self.input_username.setObjectName("input_username")
        self.input_security = QtWidgets.QLineEdit(self.centralwidget)
        self.input_security.setGeometry(QtCore.QRect(210, 290, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_security.setFont(font)
        self.input_security.setStyleSheet("QLineEdit{border:0.5px solid gray; border-radius:8px}")
        self.input_security.setText("")
        self.input_security.setObjectName("input_security")
        self.security = QtWidgets.QLabel(self.centralwidget)
        self.security.setGeometry(QtCore.QRect(130, 290, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.security.setFont(font)
        self.security.setAlignment(QtCore.Qt.AlignCenter)
        self.security.setObjectName("security")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setEnabled(False)
        self.bg.setGeometry(QtCore.QRect(0, 0, 671, 501))
        self.bg.setStyleSheet("Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(51, 156, 235), stop:1 rgb(245, 245, 245))")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.confirm_button = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_button.setGeometry(QtCore.QRect(160, 370, 381, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.confirm_button.setFont(font)
        self.confirm_button.setStyleSheet("QPushButton{color: rgb(255, 255, 255); background-color: #1dc5fc; border-radius:8px}\n"
"\n"
"QPushButton:hover{Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #23cdfc, stop:1 #1cd7fc);}\n"
"\n"
"QPushButton:pressed{Background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #1cd7fc, stop:1 #23cdfc);}\n"
"")
        self.confirm_button.setObjectName("confirm_button")
        self.text_label = QtWidgets.QLabel(self.centralwidget)
        self.text_label.setGeometry(QtCore.QRect(260, 90, 171, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(21)
        self.text_label.setFont(font)
        self.text_label.setObjectName("text_label")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(20, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet("QPushButton{color: rgb(255, 255, 255); border-radius:10px}\n"
"\n"
"QPushButton:hover{Background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));}\n"
"\n"
"QPushButton:pressed{Background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:0.1 rgba(255, 255, 255, 255), stop:0.2 rgba(255, 176, 176, 167), stop:0.3 rgba(255, 151, 151, 92), stop:0.4 rgba(255, 125, 125, 51), stop:0.5 rgba(255, 76, 76, 205), stop:0.52 rgba(255, 76, 76, 205), stop:0.6 rgba(255, 180, 180, 84), stop:1 rgba(255, 255, 255, 0));}")
        self.back_button.setFlat(True)
        self.back_button.setObjectName("back_button")
        self.bg.raise_()
        self.close_button.raise_()
        self.username.raise_()
        self.input_username.raise_()
        self.input_security.raise_()
        self.security.raise_()
        self.confirm_button.raise_()
        self.text_label.raise_()
        self.back_button.raise_()
        SecurityQuestionWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SecurityQuestionWindow)
        QtCore.QMetaObject.connectSlotsByName(SecurityQuestionWindow)

    def retranslateUi(self, SecurityQuestionWindow):
        _translate = QtCore.QCoreApplication.translate
        SecurityQuestionWindow.setWindowTitle(_translate("SecurityQuestionWindow", "MainWindow"))
        self.close_button.setText(_translate("SecurityQuestionWindow", "×"))
        self.username.setText(_translate("SecurityQuestionWindow", "账号："))
        self.input_username.setPlaceholderText(_translate("SecurityQuestionWindow", "请输入账号"))
        self.input_security.setPlaceholderText(_translate("SecurityQuestionWindow", "请输入密保"))
        self.security.setText(_translate("SecurityQuestionWindow", "密保："))
        self.confirm_button.setText(_translate("SecurityQuestionWindow", "确认"))
        self.text_label.setText(_translate("SecurityQuestionWindow", "密保验证"))
        self.back_button.setText(_translate("SecurityQuestionWindow", "←"))

